---
title: "StatComp Project 1: Numerical Statistics"
author: "Your Name (s0000000, GithubUsername)"
output:
  html_document:
    number_sections: yes
  pdf_document:
    number_sections: yes
header-includes:
  - \newcommand{\bm}[1]{\boldsymbol{#1}}
  - \newcommand{\mat}[1]{\begin{bmatrix}#1\end{bmatrix}}
---

```{r setup, include = FALSE}
# Modify this setup code chunk to set options
# or add extra packages etc if needed,
# but keep the echo=FALSE,eval=TRUE default settings here.

# Set default code chunk options
knitr::opts_chunk$set(
  echo = FALSE,
  eval = TRUE
)

suppressPackageStartupMessages(library(tidyverse))
theme_set(theme_bw())
```

```{r code=readLines("code.R")}
source("code.R")
```

```{r code=readLines("my_code.R")}
source("my_code.R")
```

# Confidence interval approximation assessment


# Archaeology in the Baltic sea

Example of code run but not shown (except for the result)
due to default chunk options. Remember to include the chunk in the
code appendix below.
```{r some-code}
# Load and display the archaeology data set
Y <- arch_data(4)
knitr::kable(Y)
```


# Code appendix

```{r code-appendix, include=FALSE}
# Change the code chunk options to display
# but not evaluate the code chunks in the appendix
knitr::opts_chunk$set(
  echo = TRUE,
  eval = FALSE
)
```

## Function definitions

```{r code=readLines("my_code.R")}
```

## Analysis code

Example for how to show code from a previous code chunk
```{r ref.label="some-code"}
```
